# Generated by Django 3.2.9 on 2021-12-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voipe_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_voipecode',
            options={'verbose_name': 'کد تلفن', 'verbose_name_plural': 'کد های تلفن'},
        ),
        migrations.RenameField(
            model_name='user_voipecode',
            old_name='user',
            new_name='id',
        ),
        migrations.AddField(
            model_name='user_voipecode',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
