# Generated by Django 3.2.9 on 2021-12-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voipe_code', '0002_auto_20211231_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_voipecode',
            name='name',
        ),
        migrations.AlterField(
            model_name='user_voipecode',
            name='voipe_code',
            field=models.CharField(max_length=50),
        ),
    ]
