# Generated by Django 3.2.9 on 2021-12-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voipe_code', '0003_auto_20211231_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_voipecode',
            old_name='id',
            new_name='user',
        ),
    ]
