# Generated by Django 3.2.9 on 2022-01-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voipe_code', '0004_rename_id_user_voipecode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_voipecode',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
